### ISSUE TITLE
Should I actually use this?

### ISSUE THREAD

**Issue by eslachance** [clojurewerkz/eep#11]
Seeing as though there has been no update for 2 years I have to ask: is this functional enough for me to use? If not (or if this is shelved indefinitely) do you know of a similar project I could use?

**Comment by michaelklishin** [comment]
We don't know your needs. We hope to spend some time on Meltdown and EEP at some point but both @ifesdjeen and I have been busy with other things in the last couple of years. I cannot name a specific alternative but there certainly should be some.

Open source is not all about consuming stuff for free, however. If something is not actively developed but you find it useful, you can always contribute.

**Comment by eslachance** [comment]
I fully understand and didn't intend on just adding this to dependencies and never touching it again. I'm actually new to Clojure but I do have a good background in making tutorials, help videos, and I've contributed with this along with a few PRs.

To be honest this really seems like what I need in the context that my first (ambitious) plan to learn clojure is a middle ware library between Discord API and client bots potentially written by other users (and myself). Coming from a node.js perspective, events are very familiar and this is why I was looking into EEP. It just seems very comfortable to me in how it works.

Apologies if I just sounded like "is this dead lol", that wasn't my intention. I greatly appreciate the effort that goes into making something like this!

I will definitely try to not only use libs like this one but also help out wherever I can. Whether it's examples, tutorials or code, I have yet to determine. Thanks for your answer! Hit me up on Clojurians Slack, I'm `luckyevie` :)

**Comment by michaelklishin** [comment]
@eslachance no worries, I definitely didn't get the "is this dead lol" impression. If you are looking to connect two different inherently async data sources then possibly Meltdown or `core.async` (the latter is opinionated and much more of a mind twister) would be sufficient. EEP is probably more suitable when you need aggregation.

If you end up using this library or Meltdown, please file issues and we'll see how we can help. It's a shame that those two are some of the least documented ClojureWerkz projects :(

**Comment by ifesdjeen** [comment]
I would recommend using meltdown over eep at that point, mostly due to the fact it utilises much simpler concepts. I didn't update meltdown for long time since reactor release was delayed. At this point I have a private meltdown fork with compatible interface but using JCTools as a queue instead of ring buffer, although I did not have enough time to prepare it for a release.
